image: node:latest

stages:
  - build
  - test

build:
  image: node:latest
  stage: build
  script:
    - npm build 
    - npm start
  cache:
    paths:
      - node_modules/
  artifacts:
    expire_in: 1 days
    when: on_success
    paths:
      - node_modules/

test:
  image: node:latest
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - build
  script:
    - npm test:ci
  artifacts:
    when: always 