image: node:alpine

stages:
  # - build
  - test

# build:
#   stage: build
#   script:
#     - echo "Hello  it worked!!"
#     - npm run build 
#     - npm run start
#   cache:
#     paths:
#       - node_modules/
#   artifacts:
#     expire_in: 1 days
#     when: on_success
#     paths:
#       - node_modules/

test:
  stage: test
  coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  # dependencies:
  #   - build
  cache:
    paths:
      - node_modules/
  script:
    - npm install
    - npm run test
  artifacts:
    when: always 

test-coverage:
  stage: test
  # coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
  dependencies:
    - test
  script:
    - npm install
    - npm run test-coverage
  artifacts:
    when: always 
    paths:
      - coverage/